name: "Deploy"
on:
  pull_request:
  push:
    branches:
      - "*"
    paths:
      - src/**
      - locales/**
      - public/**
      - vite.config.ts
      - vercel.json
      - windi.config.ts
      - package.json
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.25.0
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          # cache: 'pnpm'
      - name: "Install"
        run: "pnpm i"
      - name: "Build"
        run: "pnpm run build"
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod ./dist'
          working-directory: "./docs/.vitepress"
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
