name: "Deploy Docs"
on:
  pull_request:
  push:
    branches:
      - "*"
    paths:
      - .github/workflows/deploy-docs.yaml
      - docs/**
      - public/**
      - package.json
  workflow_dispatch:

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      # - uses: actions/checkout@v3
      #   with:
      #     repository: voxelum/minecraft-launcher-core-node
      #     path: docs/en/core
      #     ref: 'gh-pages'
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 8.2.0
      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: "Install"
        run: "pnpm i"
      - name: "Build"
        run: "pnpm run docs:build"
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          working-directory: "./docs/.vitepress"
          vercel-args: '--prod ./dist'
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.DOC_PROJECT_ID }}
